config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /fr|es|de|pt|it/ do
    root 'subscribers#new'
    resources :subscribers, only: [:create] do
      get 'survey', on: :member
      get 'thanks', on: :member
    end
  end

  post 'typeform_webhook', to: "subscribers#typeform_webhook"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :subscriber
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  validates :name, presence: true
  has_many :preferences
  has_many :subscribers, through: :preferences
end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :subscriber
  belongs_to :campaign
end

app/models/question.rb
class Question < ApplicationRecord
  default_scope { order(order: :asc) }
  has_many :answers

  def self.next(current_question)
    Question.find_by(order: current_question.order + 1)
  end
end

app/models/subscriber.rb
require 'net/http'
require 'net/https'

class Subscriber < ApplicationRecord
  has_many :preferences
  has_many :campaigns, through: :preferences
  has_many :answers, class_name: "SubscriberAnswer"

  accepts_nested_attributes_for :preferences

  validates :email, presence: true, uniqueness: true
  validates :preferences, presence: true
  validate :check_email_score

  after_create :send_welcome_email

  private

  def send_welcome_email
    SubscriberMailer.welcome_email(self).deliver_later
  end

  def make_abstract_request(email)
    #Todo: pasar api key a .env
    uri = URI("https://emailvalidation.abstractapi.com/v1/?api_key=33001481c5e54c679ab20d33c4f1f097&email=#{email}")

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    request =  Net::HTTP::Get.new(uri)

    response = http.request(request)
    return response
  rescue StandardError => error
      puts "Error (#{ error.message })"
  end

  def check_email_score
    response = make_abstract_request(self.email)

    parsed_reponse = JSON.parse(response.body)
    score = parsed_reponse["quality_score"].to_f if parsed_reponse["quality_score"]

    errors.add(:email, "Not a valid email, please provide another one") if score && score < 0.7
  end
end

app/models/subscriber_answer.rb
class SubscriberAnswer < ApplicationRecord
  belongs_to :subscriber
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    subscriber = @answer.subscriber
    current_question = @answer.question
    next_question = Question.next(current_question)
    if @answer.save
      if next_question
        redirect_to subscriber_question_path(subscriber, next_question)
      else
        subscriber.update(coupon: SecureRandom.alphanumeric(10))
        redirect_to thanks_subscriber_path(subscriber)
        SubscriberMailer.coupon_email(subscriber).deliver_later
      end
    else
      render 'questions/show'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :question_id, :subscriber_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

  # config.i18n.default_locale = :en
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @subscriber = Subscriber.find(params[:subscriber_id])
    @question = Question.find(params[:id])
    @answer = Answer.new
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:typeform_webhook]
  def new
    @subscriber = Subscriber.new

    @campaigns = Campaign.all.order(name: :desc)
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      redirect_to survey_subscriber_path(@subscriber) #'https://f3acxl7a4jh.typeform.com/to/KRfXqzoM', allow_other_host: true #root_path, notice: 'Subscribed!'
    else
      @campaigns = Campaign.all
      render :new
    end
  end

  def thanks
    @subscriber = Subscriber.find(params[:id])
  end

  def typeform_webhook
    # Here instead of using the method subscriber.find, it was more practical to use subscriber.last because we
    # have limited amount of answers in the free plan of Typeform
    subscriber = Subscriber.last
    if params["form_response"]["answers"]
      params["form_response"]["answers"].each do |answer|
        SubscriberAnswer.create(description: answer["text"],
                                subscriber: subscriber,
                                typeform_question_reference: answer["field"]["ref"])
      end
    end
    subscriber.update(coupon: SecureRandom.alphanumeric(10))
    SubscriberMailer.coupon_email(subscriber).deliver_later
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:email, preferences_attributes: [:id, :campaign_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicoletTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/show.html.erb
<!-- app/views/questions/show.html.erb -->
<h3 class="mt-3"><%= t("coupon") %></h3>
<hr>

<h1><%= t("question") %></h1>
<p><%= t("questions.#{@question.title}") %></p>

<%= form_for @answer, url: answers_path, method: :post do |form| %>
  <%= form.hidden_field :question_id, value: @question.id %>
  <%= form.hidden_field :subscriber_id, value: @subscriber.id %>
  <div>
    <%= form.text_field :content, class: "email-field" %>
  </div>

  <%= form.submit t("next"), class: "mt-3 btn-micolet" %>
<% end %>

app/views/subscribers/new.html.erb
<div class="container text-center">
  <!-- Logo -->
  <div class="mt-4">
    <%= image_tag("micolet.png", alt: "Micolet Logo", style: "width: 300px; height: 65px;") %>
    <p class="logo-slogan"><%= t("slogan") %></p>
  </div>
  <!-- Título -->
  <br>
  <br>
  <h5 class="mt-1"><%= t("welcome") %></h5>
  <h5><%= t("welcome2") %></h5>
  <!-- Texto de suscripción -->
  <h6 class="mt-4"><%= t("subscribe") %></h6>

  <br>
  <div class="row d-flex">
    <div class="col-md-4 mx-auto">
      <% if @subscriber.errors[:email].any? %>
        <div class="error">
          <%= @subscriber.errors[:email].first %>
        </div>
      <% end %>
      <%# <%= @subscriber.errors.any?%>

      <!-- Formulario de registro -->

      <%= form_for(@subscriber, url: subscribers_path, html: { data: { turbo: false } }) do |f| %>
        <div class="d-flex flex-column">
          <div class="d-flex justify-content-start">
            <%= f.label :email, style: "font-weight: bold;" %>
          </div>
          <%= f.text_field :email, class: "email-field", placeholder: t("placeholders") %>
          <div class="d-flex justify-content-start mt-1">
            <%= f.label :preferences, style: "font-weight: bold;" %>
          </div>
            <div class="mt-1">
              <%= f.fields_for  Preference.new do |p| %>
                <% @campaigns.each_with_index do |campaign, i| %>
                  <div class="d-flex">
                    <input class="me-3 checkbox-green" type="checkbox" value="<%=campaign.id%>" name="subscriber[preferences_attributes][<%=i%>][campaign_id]" id="subscriber_preferences_attributes_<%=i%>_campaign_id">
                    <label class="align-item-start" style="color: black;" for="subscriber_preferences_attributes_<%=i%>_campaign_id"><%= t("campaigns.#{campaign.name}") %></label>
                  </div>
                <% end %>
              <% end %>
            </div>
        </div>

      <%= f.submit t("subscribe1"), class: "btn-micolet mt-3" %>
    <% end %>
    </div>
  </div>
</div>

app/views/subscribers/survey.html.erb
<h3 class="mt-1"><%= t("coupon") %></h3>
<hr>
<% if Rails.env.production? %>
  <div data-tf-widget="fvA2wCW6" data-tf-opacity="100" data-tf-iframe-props="title=Micolet(production)" data-tf-transitive-search-params data-tf-medium="snippet" style="width:100%;height:500px;"></div><script src="//embed.typeform.com/next/embed.js"></script>
<%else%>
  <div data-tf-widget="RR1Zul6p" data-tf-opacity="100" data-tf-iframe-props="title=Micolet" data-tf-transitive-search-params data-tf-medium="snippet" style="width:100%;height:500px;"></div><script src="//embed.typeform.com/next/embed.js"></script>
<%end%>

<div class="container mb-1">
  <div class="row">
    <div class="col-md-12 d-flex">
      <%= button_to t("back"), root_path, method: :get, class: "btn-micolet btn-gap" %>
      <%= button_to t("visit"), "https://www.micolet.com/", method: :get, class: "btn-micolet" %>
    </div>
  </div>
</div>

app/views/subscribers/thanks.html.erb
<!-- app/views/subscribers/thanks.html.erb -->
<h1 class="mt-4"><%= t("ty") %></h1>
<hr>
<h5 class="mt-4"><%= t("disc") %></h5>
<%# <% random_code = SecureRandom.alphanumeric(10) %>
<%# <p class="mt-3"><%= random_code</p> %>
<p><%= @subscriber.coupon %></p>
<!-- Agrega aquí el código HTML para mostrar el cupón de descuento -->
<br>
<div class="container mt-3 mb-1">
  <div class="row">
    <div class="col-md-12 d-flex">
      <%= button_to t("back"), root_path, method: :get, class: "btn-micolet btn-gap" %>
      <%= button_to t("visit"), "https://www.micolet.com/", method: :get, class: "btn-micolet" %>
    </div>
  </div>
</div>